apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc-volume
spec:
  storageClassName: local-storage
  volumeName: prometheus-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
